### ISSUE TITLE
Document: Project overall documetation todo list and check through

### ISSUE THREAD

**Issue by FanWangEcon** [ClimateInequality/PrjCEC#42]
# Project documention and code organization

There are three components to project code, data, and final outputs that require documentation:

1. Data downloading and processing code:
    - function: `R` folder data processing script
    - script: `R-script` folders with `download_` prefix
    - data: data output, linkages and storage
2. Generate exposure statistics:
    - function: `R` folder statistics functions
    - script: `R-script` folder with `run_` prefix
    - data: statistics outputs in `data-res` folder
3. Generate table and figures:
    - script: `R-script` folders with `tagfig_` prefix
    - data: final data structures for each results, and specific data structures for each table/figure.

Todo:

- [ ] Functionalize and create package for components in `R` folders to be reused.
- [ ] Test all `R-script` folder components
- [ ] Make all data input and output accessible 
- [ ] General front-page documentation to guide three each of three components, with linkages to each bullet point above. 
- [ ] README file in each R-script folder, and each data input and output folder
- [ ] Improve file linkages in `download_`, `run_`, and `tabfig_` result specicifc ISSUEs files.
