### ISSUE TITLE
Core Data: Key Files

### ISSUE THREAD

**Issue by FanWangEcon** [ClimateInequality/PrjCEC#8]
## Key Files 

To match and merge and jointly use the demographic and environmental data, we need to be able to match the county-ids to geographical coordinates which are the units of measurements for the temperature data. 

Furthermore, we want to allow for potentially different layers of observables aggregations to study inequalities across population groups, time, and space at different levels of aggregation

### Part 1, Demographic Group Keys across Times

To help with the interpretation of the file. We create a demographic key file, which applies to all years. 

- name: **df_key_demo_china_census.csv**
- size: $Z_{t} \times T$ by 5 or more
- rows: $Z_{t}$ is the number of joint demographic groups in year $t$: if we have 20 age groups and 2 gender groups, then $Z=40$, this might differ across years, so we allow for that possibility, and $T$ is the total number of census years we are considering. So if we have 40 groups in 2020, and 36 groups in 2010, then we would have 76 rows. 
   - Each $Z_{t}$ is the same as the $Z$ from #7 from the **df_china_census_county_2020.csv** file.
- columns:
   - column 1: the year, 2020, 2010, etc...
   - column 2: the column ids/names from **df_china_census_county_2020** and other years. 
   - column 3: corresponding gender for the population included under the column name.
   - column 4: corresponding age group for the population included under the column name.
   - column 5 and others: additional age groupings, age/gender combinations. 
 
Use the same strings in columns whenever possible. For example, if one of the groups is age 5 to 9 and this appears in multiple census, we should use exactly the same string "Age 5 to 9" for example, for all census year rows. 

#### Generated files:

- [data/df_key_demo_china_census_1990.csv](https://github.com/ClimateInequality/PrjCEC/blob/main/data/df_key_demo_china_census_1990.csv)
- [data/df_key_demo_china_census_2020.csv](https://github.com/ClimateInequality/PrjCEC/blob/main/data/df_key_demo_china_census_2020.csv)

### Part 2, Location Key File A, coordinates to county ID

We need to be able to match counties, based on their polygon boundaries to each of the rows or extreme temperature data in the temperature file, where each row is the lowest level of geographical aggregation from ERA5. 

Note that one thing that facilitates this work is that the geographical coordinates is invariant over time because of the consistency in ERA5 data structure over time. 

While it is possible that over two census years there is limited changes in county boundary, we hope to have shape files for each year, and match each year's shape file to the correct boundaries. 

- name: **df_key_loc_china_coord2county.csv**
- size: $N$ by 6 or more
- rows: $N$ is all unique geo-coordinates-unit of observations from ERA 5, this is the same $N$ as the $N$ for the **df_era5_utci_china_2020.csv** file discussed in #6.
- columns:
   - column 1: id for units of observed geo-squares (i.e., the 0.25 km by 0.25 km square units of observation), identical to the row id from **df_era5_utci_china_2020.csv** file discussed in #6. 
   - column 2: the longitude corresponding to the geo-square
   - column 3: the latitude corresponding to the geo-square
   - column 4: county id in year 2020, there will be $C_t$ unique county-ids, the same county id as from the rows of the *df_china_census_county_2020.csv* file discussed in #7. Each county likely covers multiple 0.25 by 0.25 km squares
   - column 5: county id in year 2010, same structure as column 4
   - column 6 and more: county id in earlier years

#### Generated files:

- [data/df_key_loc_china_coord2county_1990.csv](https://github.com/ClimateInequality/PrjCEC/blob/main/data/df_key_loc_china_coord2county_1990.csv)
- [data/df_key_loc_china_coord2county_2020.csv](https://github.com/ClimateInequality/PrjCEC/blob/main/data/df_key_loc_china_coord2county_2020.csv)

Note, the population files are from University data repositories and not shared in this repository. The 1990 child population and county boundary files are from the NYU spatial data repository.

### Part 3, Location Key File B, county ID to prefecture and provinces

We want to know the relationship between county IDs and prefecture and provincial IDs. so that we can do inequality analysis at higher regions of aggregation and link to higher units/layers of observables. 

There will be duplication across years, but for precision, we keep track of all counties in each year separately to accommodate any possible variations. 

- name: **df_key_loc_china_county2province.csv**
- size: $C_t \times T$ by 6 or more
- rows: $C_t$ is the number of counties in each year, $T$ is the number of years of data
- columns:
   - column 1: The year, 2020, 2010, etc.
   - column 2: The year-specific county-id
   - column 3: Prefecture name/ID
   - column 4: Provincial name/ID
   - column 5 and more: Other unit of classification for county/prefecture that we can add to.

#### Generated files:

- [data/df_key_loc_china_county2province_1990.csv](https://github.com/ClimateInequality/PrjCEC/blob/main/data/df_key_loc_china_county2province_1990.csv)
- [data/df_key_loc_china_county2province_2020.csv](https://github.com/ClimateInequality/PrjCEC/blob/main/data/df_key_loc_china_county2province_2020.csv)

## Key Objectives

Once all shapefiles for each year is available:

- [x] I think there is existing code/functions that can do this easily: Find/develop Code/script that maps shapefile shape locations to the coordinate-geo-square this shapefile covers. A simple script that runs through all possible coordinate-geo-square, and then picks one county as the parent of this geo-square would be sufficient. When a geo-square borders multiple county, pick the one that has the largest area in the geo-square. 
- [x] Generate **df_key_demo_china_census.csv**
- [x] Generate **df_key_loc_china_coord2county.csv**
- [x] Generate **df_key_loc_china_county2province.csv**
